@startuml
class ArduinoConnector {
    + arduinoIP : string = "192.168.43.50"
    + arduinoPort : int = 12345
    + ConnectToArduino() : void
    + SendMessageToArduino(message:string) : void
}
MonoBehaviour <|-- ArduinoConnector
ArduinoConnector --> "connectionLabel" TMP_Text
@enduml
