@startuml
class ToggleMenuFollow {
    + followDistance : float = 1.5f
    + verticalOffset : float
    + horizontalOffset : float = 0f
    + ToggleFollow() : void
    + ToggleEnabled() : void
}
MonoBehaviour <|-- ToggleMenuFollow
ToggleMenuFollow --> "menu" GameObject
ToggleMenuFollow --> "exoSkeleton" GameObject
ToggleMenuFollow --> "tmpText" TMP_Text
class ArduinoConnector {
    + arduinoIP : string = "192.168.43.50"
    + arduinoPort : int = 12345
    + ConnectToArduino() : void
    + SendMessageToArduino(message:string) : void
}
MonoBehaviour <|-- ArduinoConnector
ArduinoConnector --> "connectionLabel" TMP_Text
class ControlEkoSkeleton {
    + ToggleExoskeleton() : void
    + ToggleFollow() : void
}
MonoBehaviour <|-- ControlEkoSkeleton
class SliderAngleDisplay {
}
MonoBehaviour <|-- SliderAngleDisplay
class ExoGrabApple {
    + joint2TargetAngle : float = 30f
    + joint3TargetAngle : float = 45f
    + joint4TargetAngle : float = 60f
    + joint5TargetAngle : float = 20f
    + jointMoveDuration : float = 1.0f
    + pauseBetweenJoints : float = 0.3f
    + TriggerGrabSequence() : void
}
MonoBehaviour <|-- ExoGrabApple
class EnableThumbCollider {
}
MonoBehaviour <|-- EnableThumbCollider
EnableThumbCollider --> "thumbCollider" Collider
class ExoMovements {
    + maxRotation : float = 45f
    + minRotation : float
    + resetDuration : float = 1f
    + pauseBetweenJoints : float = 0.3f
    + ResetJointsSequentially() : void
}
MonoBehaviour <|-- ExoMovements
@enduml
