@startuml
class ToggleMenuFollow {
    + followDistance : float = 1.5f
    + verticalOffset : float
    + horizontalOffset : float = 0f
    + ToggleFollow() : void
    + ToggleEnabled() : void
}
MonoBehaviour <|-- ToggleMenuFollow
ToggleMenuFollow --> "menu" GameObject
ToggleMenuFollow --> "exoSkeleton" GameObject
ToggleMenuFollow --> "tmpText" TMP_Text
class ControlEkoSkeleton {
    + ToggleExoskeleton() : void
    + ToggleFollow() : void
}
MonoBehaviour <|-- ControlEkoSkeleton
class SliderAngleDisplay {
}
MonoBehaviour <|-- SliderAngleDisplay
class ExoGrabApple {
    + joint2TargetAngle : float = 30f
    + joint3TargetAngle : float = 45f
    + joint4TargetAngle : float = 60f
    + joint5TargetAngle : float = 20f
    + jointMoveDuration : float = 1.0f
    + pauseBetweenJoints : float = 0.3f
    + TriggerGrabSequence() : void
}
MonoBehaviour <|-- ExoGrabApple
class EnableThumbCollider {
}
MonoBehaviour <|-- EnableThumbCollider
EnableThumbCollider --> "thumbCollider" Collider
class GameManager {
    + GetLeftPartPosition() : Transform
    + GetRightPartPosition() : Transform
    + GetFrontPartPosition() : Transform
    + GetBackPartPosition() : Transform
    + GetConveyorPartPosition() : Transform
    + GetConveyorDownScrewPosition() : Transform
    + GetUpPartsPosition() : Transform
    + GetConveyorJos() : GameObject
    + GetConveyorLateralStanga() : GameObject
    + GetConveyorLateralDreapta() : GameObject
    + GetConveyorSus() : GameObject
    + GetConveyorPrincipal() : GameObject
    + GetParteaFata() : GameObject
    + GetParteaSpate() : GameObject
    + GetSurubOrizontalFata() : GameObject
    + GetSurubOrizontalSpate() : GameObject
    + GetSurubVertical() : GameObject
    + GetParteaLateralaStanga() : GameObject
    + GetParteaLateralaDreapta() : GameObject
    + GetSuruburiPartiLaterale() : GameObject
    + GetDezasamblare() : GameObject
}
MonoBehaviour <|-- GameManager
GameManager --> "Instance" GameManager
class ExoMovements {
    + maxRotation : float = 45f
    + minRotation : float
    + resetDuration : float = 1f
    + pauseBetweenJoints : float = 0.3f
    + ResetJointsSequentially() : void
}
MonoBehaviour <|-- ExoMovements
@enduml
